### ISSUE TITLE
Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.

### ISSUE THREAD

**Issue by thehalfrikana** [wobsoriano/nuxt3-supabase#4]
Hi, 

I just downloaded this package but whenever I try to incorporate it into my Nuxt 3 app I get the following error:

`Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.`

However, after I downloaded the @vitejs/plugin-vue package I still received the same error. Would anyone be able to help me with this?

**Comment by wobsoriano** [comment]
Try to delete your node_modules and yarn.lock/package-lock.json and reinstall

**Comment by thehalfrikana** [comment]
I just did but now I'm getting a different error:

`Invalid value used as weak map key
  at WeakMap.set (<anonymous>)  
  at normalizePropsOptions (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2689:11)  
  at createComponentInstance (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6115:23)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:12)  
  at ssrRender (file://./.nuxt/dist/server/server.mjs:7129:31)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:263:13)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:304:22)  
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:17)`

**Comment by wobsoriano** [comment]
A minimal reproduction would be nice

**Comment by thehalfrikana** [comment]
Here's the code in my nuxt.config.ts file:

`import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  modules: ['nuxt3-supabase/module'],
  supabase: {
    supabaseUrl: process.env.SUPABASE_URL,
    supabaseKey: process.env.SUPABASE_KEY,
    //supabaseOptions: process.env.SUPABASE_OPTIONS // not required
  }
})
`
and here's the code that I've added so far to my Auth.vue component that's not working:

`<template lang="pug">
form
    div 
        div 
            input(
                type = "email"
                placeholder = "Your email"
                v-model = 'email' 
            )
        div
            input(
                type = "submit"
                :value = "loading ? 'Loading' : 'Send magic link'"
                :disabled = "loading"
            )
</template>

<style lang="sass">

</style>

<script>
export default {
    setup () {
        const { $supabase } = useNuxtApp();
        const { data, pending } = await useAsyncData('posts', () => {
            return $supabase.from('posts').select();
            }
  },
</script>`

For some reason it seems like Nuxt 3 doesn't like when I use "import" in my script tags so I removed those sections already.
